config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "welcome#index"

  get  'current_activity', to: "current_activity#index"
  post 'current_activity/start'
  post 'current_activity/stop'

  resources :activity_logs
  resources :activities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord

    has_many :current_activities
    has_many :activity_logs

    belongs_to :user

    validates :label, presence: true, length: {maximum: 255}
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
    belongs_to :activity
    belongs_to :user
    
    validates_associated :activity, presence: true
    validates :started_at, presence: true
    validates :ended_at, presence: true

    # 指定した期間のアクティビティを取得する
    scope :activity_of, 
        ->(datetime) { includes(:activity)\
            .where(started_at: datetime.beginning_of_day..datetime.end_of_day)\
            .order(started_at: :asc)\
            .references(:activity)}

    scope :today_activity, ->{ activity_of(DateTime.now) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_activity.rb
class CurrentActivity < ApplicationRecord

  belongs_to :activity
  belongs_to :user

  validates :activity, presence: false
  validates :started_at, presence: true
  
  def start(activity)
    self.activity_id = activity
    self.started_at = DateTime.now
  end

  def stop
    ca = CurrentActivity.lock.first
    al = ActivityLog.new(user: self.user, activity: ca.activity, started_at: ca.started_at, ended_at: DateTime.now)
    al.save
    ca.destroy
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :activities
  has_many :activity_logs
  has_one :current_activity

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities
  end

  # GET /activities/new
  def new
    @activity = current_user.activities.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activities_url, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activities_url, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = current_user.activities.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:label)
    end
end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity_log, only: [:show, :edit, :update, :destroy]

  # GET /activity_logs
  # GET /activity_logs.json
  def index
    @activity_logs = current_user.activity_logs.today_activity
  end

  # GET /activity_logs/1
  # GET /activity_logs/1.json
  def show
  end

  # GET /activity_logs/new
  def new
    @activity_log = current_user.activity_logs.new
  end

  # GET /activity_logs/1/edit
  def edit
  end

  # POST /activity_logs
  # POST /activity_logs.json
  def create
    @activity_log = current_user.activity_logs.new(activity_log_params)

    respond_to do |format|
      if @activity_log.save
        format.html { redirect_to activity_logs_url, notice: 'Activity log was successfully created.' }
        format.json { render :show, status: :created, location: @activity_log }
      else
        format.html { render :new }
        format.json { render json: @activity_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_logs/1
  # PATCH/PUT /activity_logs/1.json
  def update
    respond_to do |format|
      if @activity_log.update(activity_log_params)
        format.html { redirect_to activity_logs_url, notice: 'Activity log was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_log }
      else
        format.html { render :edit }
        format.json { render json: @activity_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_logs/1
  # DELETE /activity_logs/1.json
  def destroy
    @activity_log.destroy
    respond_to do |format|
      format.html { redirect_to activity_logs_url, notice: 'Activity log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_log
      @activity_log = current_user.activity_logs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_log_params
      params.require(:activity_log).permit(:activity_id, :activity, :started_at, :ended_at)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/current_activity_controller.rb
class CurrentActivityController < ApplicationController
  before_action :authenticate_user!
  
  # GET /current_activity
  def index
    @current_activity = current_user.current_activity
    respond_to do |format|
      format.html { render :index }
    end
  end

  # POST /current_activities/start
  def start
    begin
      activity = current_user.activities.find(params[:activity_id])  
    rescue ActiveRecord::RecordNotFound
      flush.now[:warn] = "Activity Not Selected."
      respond_to do |format|
        format.html { render :index }
      end
      return
    end
    ca = current_user.build_current_activity
    ca.start(activity.id)
    ca.save
    respond_to do |format|
      format.html { redirect_to current_activity_url }
    end
  end

  # POST /current_activities/stop
  def stop
    current_user.current_activity.stop
    respond_to do |format|
      format.html { redirect_to current_activity_url }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_activity_helper.rb
module CurrentActivityHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true, id:"activity-form", class: "siimple-form") do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="siimple-form-field">
    <%= form.label :label, class:"siimple-label" %>
    <%= form.text_field :label, id: :activity_label, class: "siimple-input " %>
  </div>
  <div class="siimple-form-field">
    <div id="submit-activity" class="siimple-btn siimple-btn--pink">Submit</div>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="siimple-table">
  <div class="siimple-table-header">
    <div class="siimple-table-row">
      <div class="siimple-table-cell">Label</div>
      <div class="siimple-table-cell"></div>
      <div class="siimple-table-cell"></div>
    </div>
  </div>
  <div class="siimple-table-body">
    <% @activities.each do |activity| %>
      <div class="siimple-table-row">
        <div class="siimple-table-cell"><%= activity.label %></div>
        <div class="siimple-table-cell"><%= link_to 'Edit', edit_activity_path(activity) %></div>
        <div class="siimple-table-cell"><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>
  </div>
</div>
<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activity_logs/_form.html.erb
<%= form_with(model: activity_log, local: true, id:"activity_log-form", class:"siimple-form") do |form| %>
  <% if activity_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_log.errors.count, "error") %> prohibited this activity_log from being saved:</h2>

      <ul>
      <% activity_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="siimple-form-field">
    <%= form.label :activity %>
    <%= form.collection_select(:activity_id, Activity.all, :id, :label, {}, {class:"siimple-select"}) %>
  </div>

  <div class="siimple-form-field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at, {id: :activity_log_started_at}, {class:"siimple-select"} %>
  </div>

  <div class="siimple-form-field">
    <%= form.label :ended_at %>
    <%= form.datetime_select :ended_at, {id: :activity_log_ended_at}, {class:"siimple-select"} %>
  </div>

  <div class="siimple-form-field">
    <div id="submit-activity_log" class="siimple-btn siimple-btn--pink">Submit</div>
  </div>
<% end %>

app/views/activity_logs/edit.html.erb
<h1>Editing Activity Log</h1>

<%= render 'form', activity_log: @activity_log %>

<%= link_to 'Show', @activity_log %> |
<%= link_to 'Back', activity_logs_path %>

app/views/activity_logs/index.html.erb
<div class="siimple-table">
  <div class="siimple-table-header">
    <div class="siimple-table-row">
      <div class="siimple-table-cell">Time</div>
      <div class="siimple-table-cell">Activity</div>
      <div class="siimple-table-cell"></div>
      <div class="siimple-table-cell"></div>
    </div>
  </div>
  <div class="siimple-table-body">
    <% @activity_logs.each do |activity_log| %>
      <div class="siimple-table-row">
        <div class="siimple-table-cell"><%= activity_log.started_at.strftime('%m/%d %H:%M') %> 〜 <%= activity_log.ended_at.strftime('%m/%d %H:%M') %></div>
        <div class="siimple-table-cell"><%= activity_log.activity.label %></div>
        <div class="siimple-table-cell"><%= link_to 'Edit', edit_activity_log_path(activity_log) %></div>
        <div class="siimple-table-cell"><%= link_to 'Destroy', activity_log, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Activity Log', new_activity_log_path %>

app/views/activity_logs/new.html.erb
<h1>New Activity Log</h1>

<%= render 'form', activity_log: @activity_log %>

<%= link_to 'Back', activity_logs_path %>

app/views/activity_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @activity_log.activity %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @activity_log.started_at %>
</p>

<p>
  <strong>Ended at:</strong>
  <%= @activity_log.ended_at %>
</p>

<%= link_to 'Edit', edit_activity_log_path(@activity_log) %> |
<%= link_to 'Back', activity_logs_path %>

app/views/current_activity/_controller.html.erb
<%= form_with(method: :post, url:current_activity_start_path, id:"start-form", class:"siimple-form") do |form| %>
        <div class="siimple-form-field" align="center">
            <%= form.collection_select(:activity_id, Activity.all, :id, :label, {prompt: "Select Activity"}, {class:"siimple-select"}) %>
        </div>
        <div class="siimple-form-field" align="center">
            <div id="start-activity" class="control-button siimple-btn siimple-btn--pink">START</div>
        </div>
<% end %>
<%= form_with(method: :post, url:current_activity_stop_path, id:"stop-form", class:"siimple-form") do |form| %>
        <div class="siimple-form-field" align="center">
            <div id="stop-activity" class="control-button siimple-btn siimple-btn--grey">STOP</div>
        </div>
<% end %>

app/views/current_activity/index.html.erb
<div class="siimple-content">

<% if @current_activity.present? %>
    <div class="siimple-alert siimple-alert--grey" align="center">
        記録中...
        <%= @current_activity.activity.label %>
        <%= @current_activity.started_at %>
    </div>
<% end %>

<% if flash.now[:error].present? %>
<div class="siimple-alert siimple-alert--yellow"><%= flash.now[:error] %></div>
<% end %>

<%= render partial: "controller" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Timemng</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="siimple-navbar">
      <div class="siimple-layout--left">
        <a class="siimple-navbar-title">Timemng</a>
      </div>
      <div class="siimple-layout--right">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class:'siimple-link siimple-navbar-link'%>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class:'siimple-link siimple-navbar-link' %>
        <% end %>
      </div>
    </div>

    <div class="contents">
    <% if user_signed_in? %>
      <div class="siimple-tabs">
        <% tab_class = ["siimple-tabs-tab"] %>
        <%= content_tag(:div, class:["siimple-tabs-tab", request.path_info.start_with?(current_activity_path) ? "siimple-tabs-tab--selected" : nil]) do %>
          <%= link_to("Controller", current_activity_path, class:"siimple-link") %>
        <% end %>
        <%= content_tag(:div, class:["siimple-tabs-tab", request.path_info.start_with?(activity_logs_path) ? "siimple-tabs-tab--selected" : nil]) do %>
          <%= link_to("History", activity_logs_path, class:"siimple-link") %>
        <% end %>
        <%= content_tag(:div, class:["siimple-tabs-tab", request.path_info.start_with?(activities_path) ? "siimple-tabs-tab--selected" : nil]) do %>
          <%= link_to("Activity", activities_path, class:"siimple-link") %>
        <% end %>
      </div>
    <% end %>
    <% if notice.present? %>
    <div class="siimple-alert siimple-alert--grey"><%= notice %></div>
    <% end %>
    <% if alert.present? %>
    <div class="siimple-alert siimple-alert--pink"><%= alert %></div>
    <% end %>
    <%= yield %>
    </div>
    <div class="siimple-footer" align="center">Timemng by rixwwd</div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="siimple-jumbotron" align="center">
  <div class="siimple-jumbotron-title">Welcome to Timemng</div>
  <div class="siimple-jumbotron-subtitle">Timemngは時間を記録するサービスです。</div>
  <div class="siimple-jumbotron-detail">今日一日、何をしたのか記録しましょう。</div>

  <%= link_to 'はじめる', new_user_registration_path, class:'siimple-btn siimple-btn--pink'%>
</div>